const tintColorLight = "#333333";
const tintColorDark = "#fff";

export default {
  light: {
    whiteText: "#fff",
    text: "#1f2c32",
    background: "#fff",
    tint: tintColorLight,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorLight,
    tabBackground: "#fff",
    textInverted: "#292929",
    textDark: "#292929",
    primaryDarkText: " #292929",
    textGrey: "#A6A6A6",
    profileGradientLight: "#acbfd3",
    profileGradientDark: "#0C1B32",
    darkBorder: "#c6c6c6",
    greyBorder: "#C8C8C8",
    primaryRed: "#E43F0B",
    darkBlue: "#0C1B32",
    blueOpacity: " rgba(97, 134, 162, 0.8)",
    darkBrown: "#7f6741",
    labelText: "#919191",
    buttonText: "#E43F0B",
    buttonBorder: "#000",
    textRed: "#E43F0B",
    black: "#000",
    darkGrey: "#333333",
    grey:"#ccc",
    darkBg: "#303A52",
    thumbBg: "#F4F6F8",
    greyBg: "#E7ECEF",
    chatBorder:"#dedede",
    chatText:"#1f1f1f",
  },
  dark: {
    whiteText: "#000",
    text: "#fff",
    background: "#000",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
    tabBackground: "#111",
    textInverted: "#fff",
    textDark: "#fff",
    textGrey: "#fff",
    primaryDarkText: " #fff",
    profileGradientLight: "#797978",
    profileGradientDark: "#323232",
    darkBorder: "#fff",
    primaryRed: "#797978",
    darkBlue: "#797978",
    blueOpacity: "rgba(115, 115, 115, .7)",
    darkBrown: "#797978",
    labelText: "#fff",
    buttonText: "#fff",
    buttonBorder: "#fff",
    textRed: "#fff",
    black: "#fff",
    darkGrey: "#fff",
    darkBg: "#fff",
    thumbBg: "#333",
    grey:"#333",
    greyBg: "#333",
    chatBorder:"#dedede",
    chatText:"#f8f8f8",
  },
};
